In [1]:
from pathlib import Path
import sys
import os

PROJECT_ROOT = Path.cwd().parent

import pandas as pd

In [ ]:
from src.data_paths import (
    EXPERIMENT_BASE_PATH,
    EXPERIMENT_TEXT_COMPLETED_PATH,

    DATA_DIR,
)

In [3]:
base = pd.read_csv(EXPERIMENT_BASE_PATH, encoding="utf-8")
texts = pd.read_csv(EXPERIMENT_TEXT_COMPLETED_PATH, encoding="utf-8")

additional_reqs = pd.read_csv(DATA_DIR / "all_participants_with_practice.csv", encoding="utf-8")

In [31]:
import src.constants as Con

extra_cols = ['trial_index', 'onestopqa_question_id', Con.ARTICLE_COLUMN, Con.DIFFICULTY_COLUMN, Con.BATCH_COLUMN, Con.PARAGRAPH_COLUMN]

reqs_lookup = (
    
    additional_reqs[['text_id_with_q'] + extra_cols]
    .drop_duplicates(subset='text_id_with_q')
)

texts_with_reqs = texts.merge(reqs_lookup, on='text_id_with_q', how='left')
texts_with_reqs

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,trial_index,onestopqa_question_id,article_id,difficulty_level,article_batch,paragraph_id
0,1_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,0,Adv,1,1
1,1_0_Adv_2_0,“There will be just enough water if the propor...,Which factor led to the increase in the price ...,Unfavorable weather conditions in different lo...,Instability of the international financial mar...,Warnings of water scarcity by Oxfam and the UN,Global warming,Bad weather in different locations on the planet,2,0,0,Adv,1,2
2,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,7,0,10,Adv,1,1
3,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...,8,1,10,Adv,1,1
4,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu...",36,2,10,Adv,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,3_9_Ele_3_1,SOHAY also has classes for parents and employe...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...,25,1,9,Ele,3,3
974,3_9_Ele_3_2,SOHAY also has classes for parents and employe...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily,Their family depends on the money they earn,10,2,9,Ele,3,3
975,3_9_Ele_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...,1.3 million children work in hazardous industries,23,1,9,Ele,3,4
976,3_9_Ele_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children","Assisted 2,125 children in going to school rat...",51,0,9,Ele,3,4
977,3_9_Ele_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540",65,2,9,Ele,3,4

In [43]:
left_keys = [
    'trial_index',
    Con.ARTICLE_COLUMN,
    Con.DIFFICULTY_COLUMN,
    Con.BATCH_COLUMN,
    Con.PARAGRAPH_COLUMN,
    'q_ind',
]
right_keys = ['trial','article_id', 'level', 'batch', 'paragraph_id', 'q_ind']

texts_base = (
    texts_with_reqs.rename(columns={'onestopqa_question_id': 'q_ind'})
    .merge(
        base,
        left_on=left_keys,
        right_on=right_keys,
        how='inner',
        suffixes=('', '_merged'),
    )
)
texts_base

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,trial_index,q_ind,...,d,correct_answer,a_key,b_key,c_key,d_key,answers_order,Aspan_inds,Dspan_inds,paragraph_merged
0,2_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,...,Obesity rates around the world will rise,0,0,1,2,3,[0 1 2 3],"[EBPoint(80, 128)]","[EBPoint(36, 69)]",Leading water scientists have issued one of th...
1,2_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,...,"By 2050, animal-based protein consumption will...",1,1,0,3,2,[1 0 3 2],"[EBPoint(80, 128)]","[EBPoint(36, 69)]",Leading water scientists have issued one of th...
2,2_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,...,"By 2050, animal-based protein consumption will...",1,1,0,3,2,[1 0 3 2],"[EBPoint(80, 128)]","[EBPoint(36, 69)]",Leading water scientists have issued one of th...
3,2_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,...,"By 2050, nine billion people will not have eno...",0,0,3,1,2,[0 2 3 1],"[EBPoint(80, 128)]","[EBPoint(36, 69)]",Leading water scientists have issued one of th...
4,2_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,1,0,...,There will not be sufficient water to grow eno...,3,3,2,1,0,[3 2 1 0],"[EBPoint(80, 128)]","[EBPoint(36, 69)]",Leading water scientists have issued one of th...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2_9_Ele_5_2,The British parliament has recommended that th...,"According to Nancie Prud'homme, why should Bol...",It has become increasingly common to be consid...,Because they are completely legal,Because Britain and 184 other countries suppor...,To support Bolivia's economy,Because respect for cultural rights has become...,51,2,...,Because they are completely legal,1,1,3,0,2,[2 0 3 1],"[EBPoint(86, 118)]","[EBPoint(0, 13),EBPoint(38, 40)]",The British parliament has recommended that th...
518,2_9_Ele_6_0,The decision to ban coca chewing was based on ...,What do experts believe about Bolivia?,It could set an example for other nations in r...,It is a model that people in many countries fo...,It needs more evidence to support its case for...,It should be more considerate of other nations...,Bolivia may provide an example for how other n...,67,1,...,It is a model that people in many countries fo...,0,0,3,1,2,[0 2 3 1],"[EBPoint(37, 58)]","[EBPoint(20, 28)]",The decision to ban coca chewing was based on ...
519,2_9_Ele_6_1,The decision to ban coca chewing was based on ...,What was decided based on the 1950 report?,That coca chewing should be banned,That the law banning coca chewing was not base...,That Bolivia will decrease its cocaine production,That the ban on drug trade would be lifted for...,A prohibition on chewing coca leaves was intro...,38,0,...,That the law banning coca chewing was not base...,1,1,3,2,0,[3 0 2 1],"[EBPoint(0, 28)]","[EBPoint(40, 47)]",The decision to ban coca chewing was based on ...
520,2_9_Ele_6_2,The decision to ban coca chewing was based on ...,What did supporters of drug liberalization say...,The statements of the report were not backed u...,The report can be interpreted as banning coca ...,The report presented Bolivia as a positive mod...,The report was a major step towards successful...,The report's claims were unsupported by evidence,39,2,...,The report was a major step towards successful...,1,1,0,2,3,[1 0 2 3],"[EBPoint(0, 28)]","[EBPoint(48, 58)]",The decision to ban coca chewing was based on ...
521,2_9_Ele_6_2,The decision to ban coca chewing was based on ...,What did supporters of drug liberalization say...,The statements of the report were not backed u...,The report can be interpreted as banning coca ...,The report presented Bolivia as a positive mod...,The report was a major step towards successful...,The report's claims were unsupported by evidence,39,2,...,The report was a major step towards successful...,0,0,1,2,3,[0 1 2 3],"[EBPoint(0, 28)]","[EBPoint(48, 58)]",The decision to ban coca chewing was based on ...