In [1]:
import pandas as pd

In [ ]:
from src.derived.ans_selection_confirmation import run_trial_level_pipeline

trial_level_df = run_trial_level_pipeline(
    fix_csv_path="../data_raw/full/fixations_Aanswers.csv",
    fix_tsv_path="../data_raw/unused/Fixations reports/fixations_A.tsv",
    output_csv_path="../data/select_confirm.csv",
    verbose=True,
)

Loading fix_csv from: data_raw\full\fixations_Aanswers.csv

FileNotFoundError: [Errno 2] No such file or directory: 'data_raw\\full\\fixations_Aanswers.csv'

In [1]:
from derived.select_confirm_last import get_last_areas_from_trial_level_csv

get_last_areas_from_trial_level_csv()

Loading data...
Extracting last IAs from trial-level data...
Attaching area labels (hunters)...
Attaching area labels (gatherers)...
Saving outputs...
Saved:
- ../data/hunters_last.csv
- ../data/gatherers_last.csv

(     participant_id  TRIAL_INDEX  last_ia_before_last_select  \
 0           l10_338            3                          20
 1           l10_338            4                          10
 2           l10_338            5                          10
 3           l10_338            6                          26
 4           l10_338            7                          18
 ...             ...          ...                         ...
 9714         l9_536           68                          10
 9715         l9_536           69                          19
 9716         l9_536           70                          12
 9717         l9_536           71                          36
 9718         l9_536           72                          43

      area_label_before_last_select  last_ia_before_confirm  \
 0                         answer_B                      21
 1                         answer_D                      10
 2                         answer_B                      10
 3                         answer_B                      26
 4                         answer_B                      36
 ...                            ...                     ...
 9714                      answer_C                       5
 9715                      answer_B                      21
 9716                      answer_A                      12
 9717                      answer_D                      36
 9718                      answer_A                      36

      area_label_before_confirm
 0                     answer_B
 1                     answer_D
 2                     answer_B
 3                     answer_B
 4                     answer_A
 ...                        ...
 9714                  answer_A
 9715                  answer_B
 9716                  answer_A
 9717                  answer_D
 9718                  answer_A

 [9719 rows x 6 columns],
      participant_id  TRIAL_INDEX  last_ia_before_last_select  \
 0           L41_408            3                          20
 1           L41_408            4                          20
 2           L41_408            5                          10
 3           L41_408            6                          27
 4           L41_408            7                          21
 ...             ...          ...                         ...
 9712         l9_491           54                           5
 9713         l9_491           55                          33
 9714         l9_491           56                          14
 9715         l9_491           57                          32
 9716         l9_491           58                          13

      area_label_before_last_select  last_ia_before_confirm  \
 0                         answer_C                      14
 1                         answer_C                      24
 2                         answer_A                      13
 3                         answer_A                      23
 4                         answer_A                      21
 ...                            ...                     ...
 9712                      answer_A                       8
 9713                      answer_B                      50
 9714                      answer_B                      19
 9715                      answer_A                      25
 9716                      answer_A                      14

      area_label_before_confirm
 0                     answer_A
 1                     answer_B
 2                     answer_A
 3                     answer_A
 4                     answer_A
 ...                        ...
 9712                  answer_A
 9713                  answer_A
 9714                  answer_B
 9715                  answer_A
 9716                  answer_A

 [9717 rows x 6 columns])

In [2]:
# malformed ALL_ANSWERS entries
# undefined nearest fixations

In [ ]:
fix_csv = pd.read_csv("../data_raw/full/fixations_Answers.csv")
ia_csv = pd.read_csv("../data_raw/full/ia_Answers.csv")

C:\Users\deeth\AppData\Local\Temp\ipykernel_34828\2362995178.py:1: DtypeWarning: Columns (0: CURRENT_FIX_NEAREST_INTEREST_AREA, 1: CURRENT_FIX_NEAREST_INTEREST_AREA_DISTANCE, 2: CURRENT_FIX_PRECISION_MEASURE_RMS_S2S, 3: CURRENT_FIX_PRECISION_MEASURE_SD_WINDOW) have mixed types. Specify dtype option on import or set low_memory=False.
  fix_csv = pd.read_csv("../data_raw/full/fixations_A.csv")

In [6]:
fix_tsv = pd.read_csv(
    "../data_raw/unused/Fixations reports/fixations_A.tsv",
    sep="\t",
    encoding="utf-16",
)

C:\Users\deeth\AppData\Local\Temp\ipykernel_34828\1022763449.py:1: DtypeWarning: Columns (0: CURRENT_FIX_NEAREST_INTEREST_AREA, 1: CURRENT_FIX_NEAREST_INTEREST_AREA_DISTANCE, 2: CURRENT_FIX_PRECISION_MEASURE_RMS_S2S, 3: CURRENT_FIX_PRECISION_MEASURE_SD_WINDOW) have mixed types. Specify dtype option on import or set low_memory=False.
  fix_tsv = pd.read_csv(

In [9]:
sel_con = pd.read_csv("../data/select_confirm.csv")

In [7]:
fix_csv[fix_csv['CURRENT_FIX_NEAREST_INTEREST_AREA'] == '.'][['CURRENT_FIX_NEAREST_INTEREST_AREA','CURRENT_FIX_INTEREST_AREA_ID']]

       CURRENT_FIX_NEAREST_INTEREST_AREA CURRENT_FIX_INTEREST_AREA_ID
199648                                 .                            .
199649                                 .                            .
199650                                 .                            .
199651                                 .                            .
199652                                 .                            .
199653                                 .                            .
199654                                 .                            .
199655                                 .                            .
199656                                 .                            .
199657                                 .                            .
199658                                 .                            .
199659                                 .                            .
199660                                 .                            .
199661                                 .                            .
199662                                 .                            .
199663                                 .                            .
199664                                 .                            .
199665                                 .                            .
199666                                 .                            .
199667                                 .                            .
199668                                 .                            .
199669                                 .                            .
199670                                 .                            .
199671                                 .                            .
199672                                 .                            .
199673                                 .                            .
199674                                 .                            .
199675                                 .                            .
199676                                 .                            .
199677                                 .                            .
199678                                 .                            .
415626                                 .                            .
415627                                 .                            .
415628                                 .                            .
415629                                 .                            .
415630                                 .                            .
415631                                 .                            .
415632                                 .                            .
415633                                 .                            .
415634                                 .                            .
415635                                 .                            .
415636                                 .                            .
415637                                 .                            .
415638                                 .                            .
415639                                 .                            .
415640                                 .                            .
415641                                 .                            .
415642                                 .                            .
415643                                 .                            .
415644                                 .                            .
415645                                 .                            .
415646                                 .                            .
415647                                 .                            .
415648                                 .                            .

In [8]:
fix_tsv[fix_tsv['CURRENT_FIX_NEAREST_INTEREST_AREA'] == '.'][['CURRENT_FIX_NEAREST_INTEREST_AREA','CURRENT_FIX_INTEREST_AREA_ID']]

       CURRENT_FIX_NEAREST_INTEREST_AREA CURRENT_FIX_INTEREST_AREA_ID
11514                                  .                            .
11515                                  .                            .
11516                                  .                            .
11517                                  .                            .
11518                                  .                            .
...                                  ...                          ...
717922                                 .                            .
717923                                 .                            .
717924                                 .                            .
717925                                 .                            .
717926                                 .                            .

[36061 rows x 2 columns]